### ISSUE TITLE
action: Persistent failure when building action

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/code-suggester#160]
Github Action workflow is persistently failing due to below error:
```
Build container for action use: '/home/runner/work/_actions/googleapis/code-suggester/v1/Dockerfile'.
Error: Docker build failed with exit code 1
```

[Full trace](https://github.com/googleapis/java-bigquery/pull/987/checks?check_run_id=1501969772)

**Comment by averikitsch** [comment]
This is blocking multiple PRs for example: https://github.com/googleapis/java-scheduler/pull/299

**Comment by stephaniewang526** [comment]
Thank you!
