### ISSUE TITLE
Setup npm releases

### ISSUE THREAD

**Issue by TomKristie** [googleapis/code-suggester#18]
- [ ] Have document detailing release notes i.e. changelog
- [ ] Auto-deployment based on GitHub commit comments
- [ ] Ensure auto-updated tags
- [ ] Ensure auto-updating of docs that reference any versioning

### Description
Create an automated npm release with auto-updating docs, tags, etc.

**Comment by chingor13** [comment]
@bcoe Everything should already work out of the box with release-please and the publish automation correct? We just need to merge the release PR when the first version is ready to go?

**Comment by bcoe** [comment]
@chingor13 yes, things look setup correctly to me.

**Comment by chingor13** [comment]
This is working
