### ISSUE TITLE
Libraries shouldn't emit logs

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/code-suggester#183]
I'm using this as a library in a bot.  When running locally via the CLI, it's outputting structured logs.  For the GitHub Action portion of this, that may make sense.  But for a server-side library, it should integrate with the existing logging subsystem.

**Comment by chingor13** [comment]
Would #178 with a no-op default logger solve this?

**Comment by JustinBeckwith** [comment]
yup
