### ISSUE TITLE
Not taking context into account when calculating hunk overlap

### ISSUE THREAD

**Issue by jacobrask** [googleapis/code-suggester#327]
#### Environment details

  - `code-suggester` version: 2.1.1

#### Steps to reproduce

  1. Try to create a suggestion
  2. code-suggester reports
```
No valid suggestions to make
Some suggestions could not be made
```
despite it being possible to create suggestions through the Github UI.

After some debugging, I pinpointed this to the `hunkOverlaps` function in `hunk-utils`. It incorrectly assumes that the suggested hunk and the PR hunk needs to overlap, but Github PRs allow suggestions on the PR hunk with a 3 line offset.

Changing it to something like this works for creating suggestions on my particular pull request, but what would be your suggested solution?

```
function hunkOverlaps(validHunk, suggestedHunk) {
    return (suggestedHunk.oldStart >= (validHunk.newStart - 3) &&
        suggestedHunk.oldEnd <= (validHunk.newEnd + 3));
}
```

**Comment by chingor13** [comment]
The pull request review suggestion is buggy (especially if your branch is out of sync with the base branch) and we haven't had time to investigate.

That said, this seems like it would be an ok attempt to fix this.

**Comment by SurferJeffAtGoogle** [comment]
This issue will fall OoSLO in 17 days.

**Comment by SurferJeffAtGoogle** [comment]
@bcoe Please re-assign to a member of the JS team.

**Comment by bcoe** [comment]
Applying the patch in this issue breaks a couple other tests:

1. `allows an deletion only suggestion at the start of the range`.
2.  `allows an addition only suggestion at the beginning of the range `.

I believe we would need to update other logic throughout the codebase to support the 3 line buffer GitHub supports.
