### ISSUE TITLE
Support multi-line PR code suggestion comments

### ISSUE THREAD

**Issue by TomKristie** [googleapis/code-suggester#59]
Create (a) function(s) in the

- [ ] framework-core
- [ ] CLI

where it takes as input
- [ ] the complete file content changeset is taken as input
- [ ] gnu diff string is taken as input

and automatically creates a [PR code-suggestion comment, (see step 6)](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request)

- supports multi-line comments
- preserve framework-core independence from git

**Comment by KristieTom12** [comment]
@chingor13 Great work! What's the status on the comment-pr branch? This work is on the comment-pr branch only.
