### ISSUE TITLE
Make auto PR comments more user-friendly

### ISSUE THREAD

**Issue by TomKristie** [googleapis/code-suggester#60]
Dependent on PR commenting feature to be developed first (depends on #59)

Update the PR commenting mechanism to minimize the number of comments generated while minimizing the number of unchanged text in a comment.

This reduces the number of irrelevant lines to the user which increases readability.

In this example, the entire LICENSE file only changes the date, but the code comment block range is the entire file. The GUI displays all the changed and unchanged text given the code comment block range.
![image](https://user-images.githubusercontent.com/65685417/89331099-348b4100-d65f-11ea-9336-fb4ad1337d23.png)

Ideally we'd want to reduce the unimportant text, while also minimizing the number of comments.

**Comment by chingor13** [comment]
Going to close this until we run into a use-case where this is enhancement is needed.
