### ISSUE TITLE
Separate generated types from the generated source code

### ISSUE THREAD

**Issue by TomKristie** [googleapis/code-suggester#74]
Currently the generated JavaScript and TypeScript modules are in the same directory and subdirectories. Therefore it possible to navigate into the directories and grab exported functions that are not a part of the main interface, and not intended to be used directly by users.

Confirm and implement that when the babel compiler generates JavaScript and TypeScript modules, that if the destination directories are separated, i.e. a separate directory for JavaScript files and a separate directory for just TypeScript modules, that it is  feasible and prevents users from importing non-main interface functions. This is done by updating package.json `types` property. 

See [TypeScript docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) for more information

**Comment by chingor13** [comment]
Not something we need to do. The intended public interface is exported in `index.ts` which lets developers `import {stuff} from 'code-suggester'`. We do not need to (probably can't anyways) limit them from importing from some build directory of code-suggester
